### ISSUE TITLE
Support Sentry-Symfony Version 5.0.0

### ISSUE THREAD

**Issue by f-schnabel** [1up-lab/contao-sentry-bundle#10]
Hi, recently there was a new version of getsentry/sentry-symfony released. 
It would be great if this could be supported.

References:
- Release Notes: https://github.com/getsentry/sentry-symfony/releases/tag/5.0.0
- Upgrade Guide: https://github.com/getsentry/sentry-symfony/blob/master/UPGRADE-5.0.md

**Comment by f-schnabel** [comment]
I don't see any compatibility issues with the new version so I created a PR to allow the new version to be used. See #11

**Comment by bytehead** [comment]
Closing in favor of #11
