### ISSUE TITLE
Use newest Sentry SDK

### ISSUE THREAD

**Issue by mstaack** [1up-lab/contao-sentry-bundle#4]
Hey, do you plan to upgrade this bundle for the latest 2.0 sdk from sentry?

https://github.com/getsentry/sentry-symfony/releases
https://github.com/getsentry/sentry-php/releases

I could also offer a PR, as this is needed for a project.

Cheers Max

**Comment by bytehead** [comment]
Hey Max

Not yet, since the symfony sdk in version 3.0 is still under development.
But feel free to provide a PR, always welcome! 🙂

**Comment by bytehead** [comment]
`2.0.0` is released! Thanks to @richardhj! 🎉
