### ISSUE TITLE
The twig snippet doesn't work anymore

### ISSUE THREAD

**Issue by f-schnabel** [1up-lab/contao-sentry-bundle#8]
I tried to use the snippet of the README, but this ended in the following error:
`An exception has been thrown during the rendering of a template ("Oneup\Contao\SentryBundle\Twig\ContaoSentryTwigRuntime::sentryLastEventIdFilter(): Return value must be of type ?string, Sentry\EventId returned")`

We fixed it locally via explicitly casting the LastEventId to a string, e.g.:
```php
    public function sentryLastEventIdFilter(): ?string
    {
        return (string)SentrySdk::getCurrentHub()->getLastEventId();
    }
```
A better solution would of course be to check if the LastEventId is null and only if it is not then casting it to a string.
I'm running on PHP 8.3 with Contao 4.13.35

**Comment by bytehead** [comment]
Closing in favor of #9
